---
- hosts: network
  remote_user: cumulus
  become: yes
  tasks:
    - name: copy interfaces
      copy: src=inventory/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: copy FRR daemons
      copy: src=inventory/{{ansible_hostname}}/daemons dest=/etc/frr/
    - name: copy FRR conf
      copy: src=inventory/{{ansible_hostname}}/frr.conf dest=/etc/frr/
    - name: reload networking
      command: ifreload -a
    - name: reload frr
      service: name=frr state=restarted

- hosts: server
  become: yes
  tasks:
    - name: copy interfaces
      copy: src=inventory/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: restarts servers with their new configuration
      shell: sleep 1 && shutdown -r 0
      async: 1
      poll: 0
      ignore_errors: true
    - name: Wait for everything to come back up
      local_action:
         module: wait_for
           host="{{ inventory_hostname }}"
           port=22
           delay=10
           timeout=300
